/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package botchting;


import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;


/**
 *
 * @author asim
 */
public class chating extends javax.swing.JFrame {
    
 VoiceManager vm ;
 Voice v;
    /**
     * Creates new form chating
     */
    public chating() {
        this.setTitle("Bot Chating");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spk_btn = new javax.swing.JButton();
        person = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        convertion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(77, 182, 252));

        spk_btn.setText("Send now ");
        spk_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                spk_btnMouseReleased(evt);
            }
        });

        convertion.setBackground(new java.awt.Color(77, 182, 252));
        convertion.setColumns(20);
        convertion.setRows(5);
        jScrollPane1.setViewportView(convertion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(person)
                .addGap(18, 18, 18)
                .addComponent(spk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void speak(String spk){
        
         System.setProperty("mbrola.base", "/home/asim/NetBeansProjects/loginPage_swing/Pharmecy2018/freetts/mbrol");
       String text = person.getText();
        convertion.append("You : "+text);
        convertion.append("\n");
            convertion.append("Robot : \n");
        vm =VoiceManager.getInstance();
        v=vm.getVoice("mbrola_us1");
         System.out.println(spk);
        v.allocate();
        
        v.speak(spk);
        
    }
    
    
    
    private void spk_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spk_btnMouseReleased
        // TODO add your handling code here:
        
        
        String text = person.getText();
        
        if(text.equals("omer")){
            speak("fuck you omer ");
        }
        else
        if(text.equals("hello")){
           // convertion.append("Robot : \n");
            speak("hello  .......... how   are     you ?");
        }
        else if(text.equals("fine and you ?")){
           // convertion.append("Robot : \n");
            speak("....fine!! .... what is you...r name .. please !");
            
        }
        else if(text.equals("السلام عليكم")){
            
          //  convertion.append("Robot : \n");
            speak("yaaaa hlaaa waaa ....elaaiiikoooom .. alsssaalaaam ");
        }
        
        
        else if (text.equals("سلامات")){
         //   convertion.append("Robot : \n");
           speak("yaaaaa .. zooooOll"); 
        }
        
        else if(text.equals("what is your name ?")||text.equals("name ?")){
          //  convertion.append("Robot : \n");
            speak("waaaaaaw goood question ..... i'm Robot .... and i maked by  AAsseem ...");
        }
        
        else speak("idont understand U");
       
        
    }//GEN-LAST:event_spk_btnMouseReleased

    
    
   
    
    
    public void bot(String s) throws InterruptedException{
        
        
        
        //Thread.sleep(100);
        
//         //chat.set
//        chat.setEditable(false);
//        chat.append("Bot : "+s+"\n");
//        System.setProperty("mbrola.base", "/home/asim/Desktop/Desktop/lib/freetts");
//       
//        vm =VoiceManager.getInstance();
//        v=vm.getVoice("mbrola_us1");
//        v.allocate();
//        v.speak("hello Asim");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea convertion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField person;
    private javax.swing.JButton spk_btn;
    // End of variables declaration//GEN-END:variables
}
